import { tally } from "./tally";

describe("tally", () => {
  describe("byApplying", () => {
    it("should return an object that contains a count of elements in an array according to how many match a key generated by the supplied function", () => {
      const input = [1.0, 1.1, 1.2, 2.0, 3.0, 2.2];

      const result = tally(input).byApplying(Math.floor);

      expect(result).toEqual({ 1: 3, 2: 2, 3: 1 });
    });
  });
});
