import { tally } from "./tally";

describe("tally", () => {
  describe("by", () => {
    it("should return an object that counts the elements of the array according to how many match each value of a key generated by the supplied function", () => {
      const input = [1.0, 1.1, 1.2, 2.0, 3.0, 2.2];

      const result = tally(input).by(Math.floor);

      expect(result).toEqual({ 1: 3, 2: 2, 3: 1 });
    });
  });
});
